---
- name: configure web service
  hosts: webservers
  tasks:
    - name: install web pkgs
      yum:
        name: "{{item}}"
        state: latest
      with_items:
        - httpd
        - php
        - php-mysql
    - name: control web service
      service:
        name: httpd
        state: started
        enabled: yes

- name: configure db service
  hosts: dbservers
  tasks:
    - name: install db pkgs
      yum:
        name: mariadb-server
        state: present
    - name: control db service
      service:
        name: mariadb
        state: started
        enabled: true
