# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-11 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('ip_addr', models.CharField(max_length=15)),
                ('group', models.CharField(max_length=50)),
            ],
        ),
    ]
