# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-09 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('salt', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
